CREATE SCHEMA if not exists ACCOUNT_ENTITY;

-- DROP TABLE IF EXISTS ACCOUNT_ENTITY.ACCOUNT_ENTITY;
CREATE TABLE IF NOT EXISTS ACCOUNT_ENTITY.ACCOUNT_ENTITY
(
    ID NUMBER(9,0) NOT NULL AUTO_INCREMENT,
    BALANCE FLOAT,
    USER_ENTITY_ID NUMBER(9,0) NOT NULL
);

-- ALTER TABLE ACCOUNT_ENTITY.ACCOUNT_ENTITY ADD CONSTRAINT IF NOT EXISTS PK_ACCOUNT PRIMARY KEY (id);
CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
-- ALTER TABLE ACCOUNT_ENTITY.ACCOUNT_ENTITY
--     ADD CONSTRAINT IF NOT EXISTS FK_ACCOUNT_ENTITY_ON_USER_ENTITY  FOREIGN KEY (user_entity_id) REFERENCES USER_ENTITY.USER_ENTITY (id);
