DROP ALL OBJECTS;
CREATE SCHEMA if not exists USER_ENTITY;

-- DROP TABLE IF EXISTS USER_ENTITY.USER_ENTITY;
CREATE TABLE IF NOT EXISTS USER_ENTITY.USER_ENTITY
(
    ID NUMBER(9,0) NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(70),
    PASSWORD VARCHAR(50),
    EMAIL VARCHAR(50),
    DATE_OF_BIRTH DATE
);
ALTER TABLE USER_ENTITY.USER_ENTITY ADD CONSTRAINT IF NOT EXISTS PK_USER PRIMARY KEY (id);